 -- FICHIER DE PARAMETRAGE
 CREATE OR REPLACE TABLE GPARAMGDDS (
 LIBPRD CHAR(10) CCSID 1147 NOT NULL DEFAULT '' ,
 PGMROB CHAR(10) CCSID 1147 NOT NULL DEFAULT '' ,
 BIBROB CHAR(10) CCSID 1147 NOT NULL DEFAULT '' ,
 BIBCMD CHAR(10) CCSID 1147 NOT NULL DEFAULT '' ,
 CLE    CHAR(52) CCSID 1147 NOT NULL DEFAULT '' ,
 GVERSION  CHAR(4) CCSID 1147 NOT NULL DEFAULT '' ,
 GLOG   CHAR(10) CCSID 1147 NOT NULL DEFAULT '' ) ;
 --
 LABEL ON TABLE GPARAMGDDS
 IS 'PARAMETRAGE DE GDDS.           ';
