-- LOG  GÉNÉRÉE DANS GDDS
CREATE OR REPLACE TABLE LOGGDDS (
  LOGUSER CHAR ( 10) NOT NULL WITH DEFAULT,
  LOGDATE DATE NOT NULL WITH DEFAULT,
  LOGTIME TIME NOT NULL WITH DEFAULT,
  LOGCMD VARCHAR ( 512) NOT NULL WITH DEFAULT)
  ;
--
  LABEL ON TABLE LOGGDDS
  IS 'HISTORIQUE DES COMMANDES GDDS  ';
