-- TABLE DES RESULTAT D'ANALYSE DE SOURCES
CREATE OR REPLACE TABLE LSTINST (
 SRCSEQ NUMERIC(6, 2) NOT NULL ,
 SRCDAT NUMERIC(6, 0) NOT NULL ,
 SRCDTA CHAR(80) CCSID 1147 NOT NULL );
--
  LABEL ON TABLE LSTINST
  IS 'LISTE DES INSTRUCTIONS GDDS  ';


